{
 "title": "Taupunkt",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Temperatur",
   "type": "timeseries",
   "description": "Temperatur aller 5 Sensoren",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "ext",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DHT22",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "ext" }
     ]
    },
    {
     "alias": "NO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DHT22",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "NO" }
     ]
    },
    {
     "alias": "SO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DHT22",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "SO" }
     ]
    },
    {
     "alias": "SW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DHT22",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "SW" }
     ]
    },
    {
     "alias": "NW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DHT22",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "NW" }
     ]
    }
   ]
  },
  {
   "title": "Radon",
   "type": "timeseries",
   "description": "Radon Strahlung in Bq/m³",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bq/m³" } },
   "targets": [
    {
     "alias": "radon",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "RD200",
     "select": [
      [
       { "params": [ "radon" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "relative Luftfeuchtigkeit",
   "type": "timeseries",
   "description": "relative Luftfeuchtigkeit aller 5 Sensoren",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "ext",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DHT22",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "ext" }
     ]
    },
    {
     "alias": "NO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DHT22",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "NO" }
     ]
    },
    {
     "alias": "SO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DHT22",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "SO" }
     ]
    },
    {
     "alias": "SW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DHT22",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "SW" }
     ]
    },
    {
     "alias": "NW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DHT22",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "NW" }
     ]
    }
   ]
  },
  {
   "title": "Fehler",
   "type": "state-timeline",
   "description": "Fehler aller Sensoren",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "alias": "ext",
     "measurement": "DHT22",
     "query": "SELECT \"error\" FROM \"DHT22\" WHERE (\"key\"::tag = 'ext') AND $timeFilter",
     "select": [
      [
       { "params": [ "error" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "ext" }
     ]
    },
    {
     "alias": "NO",
     "measurement": "DHT22",
     "select": [
      [
       { "params": [ "error" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "NO" }
     ]
    },
    {
     "alias": "SO",
     "measurement": "DHT22",
     "select": [
      [
       { "params": [ "error" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "SO" }
     ]
    },
    {
     "alias": "SW",
     "measurement": "DHT22",
     "select": [
      [
       { "params": [ "error" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "SW" }
     ]
    },
    {
     "alias": "NW",
     "measurement": "DHT22",
     "select": [
      [
       { "params": [ "error" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "NW" }
     ]
    },
    {
     "alias": "Radon",
     "measurement": "RD200",
     "select": [
      [
       { "params": [ "error" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Taupunkt",
   "type": "timeseries",
   "description": "Taupunkte aller 5 Sensoren",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "ext",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DHT22",
     "select": [
      [
       { "params": [ "dewpoint" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "ext" }
     ]
    },
    {
     "alias": "NO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DHT22",
     "select": [
      [
       { "params": [ "dewpoint" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "NO" }
     ]
    },
    {
     "alias": "SO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DHT22",
     "select": [
      [
       { "params": [ "dewpoint" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "SO" }
     ]
    },
    {
     "alias": "SW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DHT22",
     "select": [
      [
       { "params": [ "dewpoint" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "SW" }
     ]
    },
    {
     "alias": "NW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DHT22",
     "select": [
      [
       { "params": [ "dewpoint" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "NW" }
     ]
    }
   ]
  },
  {
   "title": "Entscheidungsfindung",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "alias": "radon_request",
     "measurement": "ventilation",
     "select": [
      [
       { "params": [ "radon_request" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "humidity_request",
     "measurement": "ventilation",
     "select": [
      [
       { "params": [ "humidity_request" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "dewpoint_granted",
     "measurement": "ventilation",
     "select": [
      [
       { "params": [ "dewpoint_granted" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "internal_temp_granted",
     "measurement": "ventilation",
     "select": [
      [
       { "params": [ "internal_temp_granted" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "external_temp_granted",
     "measurement": "ventilation",
     "select": [
      [
       { "params": [ "external_temp_granted" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "in_fan_on",
     "measurement": "switches",
     "select": [
      [
       { "params": [ "in_fan_on" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "out_fan_on",
     "measurement": "switches",
     "select": [
      [
       { "params": [ "out_fan_on" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperatur",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "ext",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "DHT22",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "ext" }
     ]
    },
    {
     "alias": "NO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "DHT22",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "NO" }
     ]
    },
    {
     "alias": "SO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "DHT22",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "SO" }
     ]
    },
    {
     "alias": "SW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "DHT22",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "SW" }
     ]
    },
    {
     "alias": "NW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "DHT22",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "NW" }
     ]
    }
   ]
  },
  {
   "title": "relative Luftfeuchtigkeit",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "ext",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "DHT22",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "ext" }
     ]
    },
    {
     "alias": "NO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "DHT22",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "NO" }
     ]
    },
    {
     "alias": "SO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "DHT22",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "SO" }
     ]
    },
    {
     "alias": "SW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "DHT22",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "SW" }
     ]
    },
    {
     "alias": "NW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "DHT22",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "NW" }
     ]
    }
   ]
  },
  {
   "title": "Taupunkt",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "ext",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "DHT22",
     "select": [
      [
       { "params": [ "dewpoint" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "ext" }
     ]
    },
    {
     "alias": "NO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "DHT22",
     "select": [
      [
       { "params": [ "dewpoint" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "NO" }
     ]
    },
    {
     "alias": "SO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "DHT22",
     "select": [
      [
       { "params": [ "dewpoint" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "SO" }
     ]
    },
    {
     "alias": "SW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "DHT22",
     "select": [
      [
       { "params": [ "dewpoint" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "SW" }
     ]
    },
    {
     "alias": "NW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "DHT22",
     "select": [
      [
       { "params": [ "dewpoint" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "key::tag", "operator": "=", "value": "NW" }
     ]
    }
   ]
  }
 ]
}